#!/usr/bin/env python3
# http://github.com/perplexa

import argparse
import asyncio
import collections
import logging
import random
import subprocess
import sys

from concurrent.futures import ProcessPoolExecutor

colors = range(30, 223)
logging.basicConfig(level=logging.INFO, format='%(message)s')

def colorize(message, color):
    return '\033[38;5;{c}m{m}\033[0m'.format(m=message, c=color)

def log(pod, message, color, width):
    pod = colorize('{p:{w}}'.format(p=pod, w=width), color)
    logging.info('[{p}] {m}'.format(p=pod, m=message))

def clean(pod):
    return pod.replace('pods/', '', 1)

def pods(labels):
    pods = subprocess.run([
            "kubectl", "get", "pods",
            "-o", "name",
            "-l", labels],
        stdout=subprocess.PIPE)
    pods = pods.stdout.decode().strip().split('\n')

    width = max(map(len, pods))
    return [(clean(p), random.choice(colors), width) for p in pods if p]

def subscribe(pod, color, width):
    print('Subscribing to log of pod ' + colorize(pod, color))
    pipe = subprocess.Popen([
            "kubectl",
            "logs",
            "--tail", "10",
            "--follow", pod],
        stdout=subprocess.PIPE)

    while True:
        if pipe.poll() is not None:
            break
        log(pod, pipe.stdout.readline().decode().rstrip(), color, width)

if __name__ == '__main__':
    parser = parser = argparse.ArgumentParser(prog='kslurp')
    parser.add_argument(
        '-l','--selector',
        help="Selector (label query) to filter on, supports '=', '==', and '!='.",
        required=True)
    args = parser.parse_args()

    podl = pods(args.selector)

    if not podl:
        print('Could not find any pods with selector: {}'.format(args.selector), file=sys.stderr)
        sys.exit(1)

    executor = ProcessPoolExecutor(len(podl))
    loop = asyncio.get_event_loop()

    for pod, color, width in podl:
        asyncio.ensure_future(loop.run_in_executor(executor, subscribe, pod, color, width))

    try:
        loop.run_forever()
    except KeyboardInterrupt:
        print("\rExiting..")

